server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
logging:
  level: INFO
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
      logFormat: '{"time": "%d{HH:mm:ss.SSS}", "message": %msg}%n'