server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
logging:
  level: INFO
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
      logFormat: '{"source": "%logger", "level": "%level", "message": %msg}%n'